development:
  adapter: mysql
  database: demolibrary
  encoding: utf8
  username: "demolibrary"
  password: "nasdaq"
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: demolibrary
  encoding: utf8
  username: "demolibrary"
  password: "nasdaq"
  host: localhost